src/15utility.js
Fixed bug where Date instance is turned into a string on update.
=> Fixed updated related bug

README.md
For #440
Added note to use script-loader for alasql with webpack
=> #440: Webpack and alasql - documentation note?

src/55functions.js
i kept getting TypeError: y.toUpperCase is not a function,
my temp fix is overwriting the function like so:
alasql.fn.UPPER = function(s) {
return String(s).toUpperCase();
}
This should fix it at the source.
=> fix UPPER and LOWER

test/test404.js
Fleshed out test404.js.
References: #518
=> spiff up test404.js

src/10start.js
=> Small misspelling

src/59convert.js, test/test431.js
It seems like a copy-paste typo got into getMinutes from getMonth.
=> Time conversion fix for 8 and 108 formats

README.md, src/15utility.js, src/18promise.js, src/833xlsx.js, src/84from.js, src/91indexeddb.js
And it seems like my editor removes trailing whitespace
=> 583: Added guides for Webpack and Browserify

README.md, src/15utility.js, src/18promise.js, src/833xlsx.js, src/84from.js, src/91indexeddb.js
#562 
I seriously don't know why this won't auto-merge. Maybe it's because I reverted a change for this commit
=> Just get global changes 

src/420from.js, src/60createtable.js, test/test604.js
Some changes to get select from view to work with localStorage. New test case shows more problems with localStorage.
Hopefully I have not missunderstod it completly:-)
=> [WIP] CREATE VIEW error with localStorage engine #604

dist/alasql.d.ts
you can use import * as alasql from "alasql" 
juste install with npm.
=> export typescript definition for native import

src/38query.js
Hello,
Just found another undeclared variable when bundling 0.3.2.
Will you want the changed dist files as well or do you compile them only at release time?
Thanks again for alasql !
=> Add missing var declaration

src/60createtable.js, src/72delete.js, test/test393.js
I've implemented the feature to trigger a function after DELETE. There is no information about the change itself, only that it is changed. But that is exactly what I need in my own project.
=> Implement TRIGGER AFTER DELETE

src/70insert.js
Causes issues when "use strict" is declared
=> "selectfn" is not declared

README.md
=> Additional webpack documentation

src/15utility.js
=> add react native support, add in read/write/delete/exists methods

README.md
=> Fix many typos and wording in README.md

README.md
Adding information about react-native and explaining the reasoning behind ignoring or not ignoring certain modules.
=> #892, #913

dist/alasql.fs.js, dist/alasql.js, src/60createtable.js, test/test616.js
=> Use created database id on foreign key check as default database id

README.md
=> Update copyright year.

LICENSE, README.md
The obvious spelling and formatting nits were addressed
=> README cleanup

src/55functions.js
Change sort from (default) lexicographical sort to a numerical sort.
This resolves #1159
=> Updated Sort Function will fix #1159

src/61date.js
[Link to issue](https://github.com/AlaSQL/alasql/issues/1389)
=> COALESCE with null argument

src/15utility.js
Currently the function utils.xlsnc does not calculate correctly columns beyond ZZ (position 701).
This change allos it to manage column names with 3 letters according to excel naming conventions.
=> Correction to utils.xlsnc to allow AAA and more

src/15utility.js
=> Calculate columns beyond ZZ for excel export (#1548)

src/91indexeddb.js
=> Remove duplicate `createDatabase` - fix #1557

README.md
=> Readme: dead links

src/15utility.js, src/50expression.js
Don't know how you have gotten away with calling `obj.constructor()` without using new.
=> convert expressions to classes

src/24view.js, src/25queryclass.js, src/45union.js, src/46apply.js, src/47over.js
=> Refactor to using classes

test/test251.js
Closes #1190 . Allows Windows compatibility for test 251
=> Make test 251 compatibility with Windows

src/59convert.js
Have refactored the code to allow for the reuse of the method
Related to #1718
=> refactored code to increase reuse of the date formatting code
