AlaSQL/alasql

package.json
When i try for example ```npm test``` for running tests i got this error on windows 
```
> npm test
alasql@0.2.2 test C:\Work\alasql
gulp && cd test && ../node_modules/.bin/mocha . --reporter dot
[20:58:03] Using gulpfile C:\Work\alasql\gulpfile.js
[20:58:03] Starting 'js-merge'...
[20:58:03] Starting 'js-merge-worker'...
[20:58:03] Starting 'plugin-prolog'...
[20:58:03] Finished 'plugin-prolog' after 781 us
[20:58:03] Starting 'plugin-plugins'...
[20:58:03] Finished 'plugin-plugins' after 1.18 ms
[20:58:03] Finished 'js-merge-worker' after 187 ms
[20:58:13] Finished 'js-merge' after 10 s
[20:58:13] Starting 'default'...
[20:58:13] Finished 'default' after 5.6 us
'..' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for …
```
=> Fix running npm scripts on windows

src/23table.js, src/60createtable.js
Instead of throwing a generic "Violation of CHECK constraint", a violation now throws "Violation of CHECK constraint {constraint_name}".
=> Include check constraint names in violation errors

src/55functions.js
Right now, unknown SQL function calls are transpiled to empty strings, which results in cryptic errors. This PR solves this by transpiling unknown_function(a, b) to alasql.fn.unknown_function(a, b) regardless of whether alasql.fn.unknown_function is actually defined, while still respecting alasql's stdfns. This also allows folks to define the implementation of functions after the fact, which I require in one of my projects.
=> Allow unknown functions to be defined on alasql.fn afterwards

src/15utility.js
It seems that `window.indexedDB` is `null` when it is not available. I've faced a problem alasql raises runtime error on ios8+chrome and found it is caused since `(typeof utils.global.indexedDB !== 'undefined');` returns true when `window.indexedDB` is `null`.
=> Fix hasIndexedDB

src/50expression.js
Like undefined, null should be treated as NULL.
=> Conflate null and undefined

dist/alasql.d.ts
Implicit any causes compiler errors if noImplicitAny flag is enabled.
=> Remove implicit any in definition file

README.md
It linked to the google maps page before the correction.
Thank you for the time you are putting into AlaSQL. Really appreciate it.
=> Minor README correction: wiki link for google spreadsheets.

package.json
My editor was complaining about two errors in package.json:
* `typings` key was duplicated.
* `engines` key had an invalid value: array instead of object. As I don't know what the minimum supported node version is, I put `"*"`.
=> fixed duplicate key + engines syntax error in package.json

dist/alasql.js, src/60createtable.js
changed the error message when foreign key constraint falis, from "undefined" table name to the actual table name,in the file alasql.js.
This is with respect to the issue #1009
=> Changed the error message when foreign key constraint fails

.travis.yml
both node 8 and 11 are no longer maintained as of 2020/1/1 and node 8 also fails to build due to the fact that one of the dependencies now requires node >=10. update list of node to test against
https://nodejs.org/en/about/releases/
=> Adjust node versions in travis

test/test046.js, test/test433.js
fix #1135 
As can be seen in the following snippets, deepEqual behavior has changed in node 12 where it became stricter. Update the test cases to accurately reflect the current behavior. We can discuss whether alasql should return array of arrays in these situations separately. 
https://runkit.com/forestfang-stripe/deep-equal-array/1.0.0
https://runkit.com/forestfang-stripe/deep-equal-array/2.0.0
=> Fix tests for node 12+

dist/alasql-worker.js, dist/alasql-worker.min.js, dist/alasql.fs.js, dist/alasql.js, dist/alasql.min.js, src/423groupby.js, src/55functions.js, test/test415.js
Fix MIN/MAX and GREATEST/LEAST to work on date and string by actively compare with `<` and `>` instead of `Math.min` and `Math.max`. This is commonly supported by other SQL engine: https://www.w3resource.com/sql/aggregate-functions/min-function.php
Currently, `MIN/MAX` works for Date but the data type changes to number, which is not what user would expect.
Fix QUART/MEDIAN to use custom comparator with `<` and `>`. When comparator is not supplied, Javascript coerce arguments to string:
>If omitted, the array elements are converted to strings, then sorted according to each character's Unicode code point value.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
Enabled skipped tests on these functions and update tests for new and correct behaviors …
=> fix QUART/MEDIAN/MIN/MAX on number/date/string

src/423groupby.js, test/test812.js
Excludes `null` cells from `COUNT` and `AVG`.
It seemed a bit odd that this had to be updated in 3 areas to take effect to the `GROUP BY` as well, should prob be abstracted into a function or something simpler. I saw there was an issue talking about `v2` and I'm not familiar with the code base, so I thought it was better just to make the necessary updates instead of trying to refactor. 😅
=> Do not include null in COUNT or AVG fixes #1251

src/38query.js, test/test813.js
fixes #927 
We currently have a fallback check on empty `query.groups` so that we can populate aggregate function default value in a non-groupby SELECT. i.e. `SELECT COUNT(1) as c FROM ? WHERE 1 = 2` should return `[{c:0}]`.
However, `query.groups` can also be empty if there is no input data to group by. In this case, we would expect AlaSQL (and other SQL engines indeed) to not return anything instead of emitting an undefined group. Add an additional check to verify that `allgroups` are empty, that is, there were no GROUP BY clause.
=> Return empty results in group by when input is empty

src/50expression.js, src/55functions.js, test/test815.js, test/test816.js
Fixes https://github.com/AlaSQL/alasql/issues/1426
During `ast.toString()`, the function alias is being set in two places: At the `yy.FuncValue` level and the `yy.Select` level. This is causing double aliases to be generated for functions when stringifying the AST, e.g. `SELECT LENGTH(col) AS length AS length`. 
This problem would have existed on other tokens such as `yy.Literal`s too, but they seem to use an outdated(?) `this.alias` which always returns `undefined`. Updating the `yy.Literal` code to use `this.as` causes the problem to appear for literals too, e.g. `SELECT col AS c AS c`.
My solution is to just remove any alias handling-code from tokens which could represent columns, and let `yy.Select` handle those aliases as it currently does.
=> Fix: AST to string causes double aliases

src/830into.js
This allows for one to set a `global.document = document` in Node via the likes of JSDom to query HTML one has parsed in Node (on the server side).
A better approach might be allowing the user to supply the document object as an option, but as it seems you don't really accept options in the constructor, I thought this might be as easy.
One other item this PR doesn't handle is that it is possible that `SELECT * FROM TXT('#one')` could be supported in Node too.
=> Check for global `document` rather than `exports` with INTO HTML

src/61date.js, test/test815.js, test/test845.js
[Issue #1287](https://github.com/agershun/alasql/issues/1287)
=> Break: NOW() returning ISO format

src/55functions.js, test/test413.js
The concat_ws function is fixed according to the [documentation](https://www.w3schools.com/sql/func_mysql_concat_ws.asp):
"... An expression with a NULL value will be skipped"
=> fix: Let CONCAT_WS ignore null

src/61date.js, test/test408.js
The DATEADD function currently accepts uses fixed intervals, for example, for a MONTH interval it always uses 30 days. But months can be of different duration. The same with the QUARTER and YEAR.
Fixed it. Also fixed the DATEADD function test.
=> fix: DATEADD does not take into account the value of the specified date

src/38query.js, src/423groupby.js, test/test020.js, test/test846.js
Hi @mathiasrw 
I tried to fix the following issues please verify and suggest if any changes are required.
https://github.com/AlaSQL/alasql/issues/1533
https://github.com/AlaSQL/alasql/issues/1532
https://github.com/AlaSQL/alasql/issues/1531
=> Sum, max, min null value fix on non numeric column

src/15utility.js
I really do not like that you have logic for loading data in certain ways, like using fetch, xhr, fs etc
i think the developer should be responsible for loading them themself if they need to do it.
Just doing this to fix one test case. not that I'm dependent on this sync version... i really think this should be removed. it's better to just use fetch instead of xhr, would work in service workers too where xhr isn't available
using responseType = 'text' is not necessary, b/c that's the default anyways.
otherwise Chrome complains on `can't set responseType when using sync xmlhttprequest`
=> Fix sync XMLHttpRequest

.eslintrc.yml, package.json, src/20database.js, src/21transaction.js, yarn.lock
Also added eslint to dev dependency so that I could run `npm run lint`
knowing what was wrong showed me that some eslintrc config had to be changed to allow for things such as reseved class keyword. also had to change stuff to allow for class fields
fyi, `commited` was changed to `committed` - hope that it don't break anything 
(got a [code spelling checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) extension in vscode)
having it on shows a LOT of blue squiggly lines over all files cuz your naming convention is more like: 
`transactionid` instead of: 
`transactionId`
it can read words that are CamelCase. It really helps me a lot of making such a silly mistake like this when english isn't your native spoken lanugage
=> Refactor transactions into a class

src/15utility.js, src/833xlsx.js
IE9 (and 10, 11) are long dead. nobody is using it anymore
=> Remove ie9 specific code

src/17alasql.js
use less of `alasql.options[xxx] = ` and instead write an object.
Also switched some comments to jsdoc comments so they are better documented and IDE friendlier
=> Restructure source using object for alasql.options

src/50expression.js, test/test819.js
For case:
`SELECT COUNT(*) FROM ? GROUP BY CASE WHEN id IS NULL THEN alternativeId ELSE id END
>>> SyntaxError: Unexpected token ']'
`
Сause: in the file '423groupby.js' there are many places similar to col2.split('\t'), but in toJS() we use template literals with a lot of \t.
=> fix: GROUP BY with CASE x IS NULL

src/70insert.js
**What is the PR `for?**
- It is an attempt to fix the issue [#1616](https://github.com/AlaSQL/alasql/issues/1616)
**Description**  : 
- It seems that the statement `alasql.exec('SELECT * FROM t2 WHERE val = (SELECT val FROM t3 WHERE id= 2)')` work fine without throwing any errors.  And the ast object has statement property which contain sql statement itself at index 0. this property contains `queries object`. Something like this :
```js
SELECT * FROM t2 WHERE val = SELECT val FROM t3 WHERE id = 2
statements: (1) [yy.Select]
0: SELECT * FROM t2 WHERE val = SELECT val FROM t3 WHERE id = 2
columns: (1) [Column]
from:  (1) [Table]
queries: (1) [yy.Select]    // <-   This property is present here
where:  val = SELECT val FROM t3 WHERE id = 2
```
-  But for the statement `alasql.exec('INSERT …
=> Fix (#1616): INSERT INTO with a SELECT * FROM and a subquery throws exception

src/38query.js, test/test1415.js
**What is the PR `for?**
- This is an attempt to fix the issue [#1415](https://github.com/AlaSQL/alasql/issues/1415).
- It seems that empty objects where due to `query.columns.length = 0`. That is why `res` and `res2` had empty objects like this `{}`. May be the solution should make sure that `query.columns.length !=0`.  
- The solution in this pr might be a bad approach to resolve the issue. But if there are any feedback or issues related to my current solution than i could try to work on different approach too.🙂
**Examples :**
```js
var data1=[{a:'abc'},{a:'xyz'}];
var data2=[{a:'123'},{a:'987'}];
var res = alasql("select * from :a union select * from :b",{a:data1,b:data2});
console.log(res); // [ { a: '123' }, { a: '987' }, { a: 'abc' }, { a: 'xyz' } ]
var res2 = alasql("select * from …
```
=> fix #1415: UNION not returning correct result

types/alasql.d.ts
I had always fought with importing alasql in typescript... 
The solution I used - 
declare module "alasql";
in my own typings.d.ts files, and losing all of the types for it.
Because - 
previous exports didn't reflect what was actually exported from the library.
previously:
import alasql from "alasq";
gave typings, but alasql was undefined.
import * as alasql gave the correct imported value, but typscript threw error "import("[..]/node_modules/alasql/types/alasql")' has no call signatures"\
Now you can 
import * as alasql from "alasq";
or
import alasql = require("alasql")
and both give valid types AND is callable at runtime
This could be fixed - ir the actual js exports, which would be more dangerous, or just in typings. So I chose this route.
=> fix: .d.ts exports

src/77declare.js, test/test1645.js
Added a fix for issue #1645 
The reference to `this` was getting modified to the window object which led to the statement not being able to resolve properly. Changing that fixed the issue.
Have also replaced the `.map` with a `.forEach` since the map is being used like a forEach
=> Added a fix for the variable assignment not working properly

src/91indexeddb.js, test/test1409.js
Fix for issue reported inside #1409 
Added support for post insert hook for indexedDb Databases.
=> Added support for post insert triggers for indexdb

src/91indexeddb.js, test/test1556.js
I have added a fix for the issue: #1556 .
If the keyPath is not present in the value, then I'm creating a object with rowKey as key of the object and returning as ` {shell_id_key: 'random_value2'}` where `shell_id_key` is the rowKey. 
=> fix(IndexedDB): Added fix when there is no keyPaths(columns) in indexDB
